CREATE DATABASE LIVRO;

USE LIVRO;

DROP TABLE IF EXISTS LIVRO;
DROP TABLE IF EXISTS LIVRO_AUTOR;
DROP TABLE IF EXISTS EDITORA;
DROP TABLE IF EXISTS LIVRO_COPIAS;
DROP TABLE IF EXISTS LIVRO_EMPRESTIMO;
DROP TABLE IF EXISTS UNIDADE_BIBLIOTECA;
DROP TABLE IF EXISTS USUARIO;


 
 CREATE TABLE LIVRO
 (Cod_livro		INTEGER NOT NULL,
 Titulo			VARCHAR(40) NOT NULL,
 Nome_editora	VARCHAR(50) NOT NULL,
 PRIMARY KEY (Cod_livro),
 FOREIGN KEY (Nome_editora) REFERENCES EDITORA(Nome)
 );

 CREATE TABLE LIVRO_AUTOR
 (Cod_livro		INTEGER NOT NULL,
 Nome_autor		VARCHAR(50) NOT NULL,
 PRIMARY KEY (Cod_livro, Nome_autor),
 FOREIGN KEY (Cod_livro) REFERENCES LIVRO (Cod_livro)
 );

 CREATE TABLE EDITORA
 ( Nome			VARCHAR(50) NOT NULL,
 Endereco		VARCHAR(50),
 Telefone		INTEGER,
 PRIMARY KEY (Nome),
 );

 CREATE TABLE LIVRO_COPIAS
 ( Cod_livro	INTEGER NOT NULL,
 Cod_unidade	INTEGER NOT NULL,
 Qt_copia		INTEGER,
 PRIMARY KEY (Cod_Livro, Cod_unidade),
 FOREIGN KEY (Cod_Livro) REFERENCES LIVRO (Cod_livro),
 FOREIGN KEY (Cod_unidade) REFERENCES UNIDADE_BIBLIOTECA(Cod_unidade)
 );

 CREATE TABLE LIVRO_EMPRESTIMO
 ( Cod_livro	INTEGER NOT NULL,
 Cod_unidade	INTEGER			NOT NULL,
 Nr_cartao		INTEGER			NOT NULL,
 Data_emprestimo DATE,
 Data_devolucao	DATE,
 PRIMARY KEY ( Cod_livro, Cod_unidade, Nr_cartao ),
 FOREIGN KEY (Cod_livro) REFERENCES LIVRO (Cod_livro),
 FOREIGN KEY (Cod_unidade) REFERENCES UNIDADE_BIBLIOTECA ( Cod_unidade),
 FOREIGN KEY (Nr_cartao) REFERENCES USUARIO (Num_cartao)
 );

 CREATE TABLE UNIDADE_BIBLIOTECA
 ( Cod_unidade	INTEGER			NOT NULL,
 Nome_unidade	VARCHAR(40)		NOT NULL,
 Endereco		VARCHAR(50),
 PRIMARY KEY (Cod_unidade),
 );

 CREATE TABLE USUARIO
 ( Num_cartao	INTEGER			NOT NULL,
 Nome			VARCHAR(40)		NOT NULL,
 Endereco		VARCHAR(50),
 Telefone		INTEGER,
 PRIMARY KEY ( Num_cartao),
 );

