RADIX DEC
#INCLUDE <P16F628A.INC>		;ARQUIVO PADRÃO MICROCHIP PARA 16F628A
__CONFIG H'3F10'

	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE USUÁRIO
	CONTADOR1
	CONTADOR2
	CONTADOR3
	ENDC			;FIM DO BLOCO DE MEMÓRIA		

#DEFINE	BOTAO	PORTA,2	;PORTA DO BOTÃO
					; 0 -> PRESSIONADO
					; 1 -> LIBERADO

#DEFINE	LED0	PORTB,0	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO

#DEFINE	LED1	PORTB,1	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO

#DEFINE	LED2	PORTB,2	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO

#DEFINE	LED3	PORTB,3	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO

#DEFINE	LED4	PORTB,4	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO

#DEFINE	LED5	PORTB,5	;PORTA DO LED
				; 0 -> APAGADO
				; 1 -> ACESO


	ORG	0x00		;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	

INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0			;ALTERA PARA O BANCO 1
	MOVLW	B'00000100'
	MOVWF	TRISA		;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SAÍDAS
	CLRF	TRISB		;DEFINE TODO O PORTB COMO SAÍDA
	CLRF	INTCON		;TODAS AS INTERRUPÇÕES DESLIGADAS
	BCF STATUS, RP0 ;RETORNA PARA O BANCO 0
	MOVLW	B'00000111'
	MOVWF	CMCON


REPETE
;LED0 POR 2S
	BSF LED0
	CALL ATRASO
	CALL ATRASO
;LED1 POR 4S
 	BCF LED0
	BSF LED1
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
;LED2
	BCF LED1
	BSF LED2
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
;LED3
	BCF LED2
	BSF LED3
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
;LED4
	BCF LED3
	BSF LED4
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
;LED3
	BCF LED4
	BSF LED3
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
;LED2
	BCF LED3
	BSF LED2
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
;LED1
	BCF LED2
	BSF LED1
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	CALL ATRASO
	BCF LED1
;REINICIAR
	GOTO REPETE

; ATRASO 1.000241S
ATRASO
	MOVLW	22
	MOVWF	CONTADOR3	;INICIA CONTADOR3

ATRASO3					
	MOVLW	63
	MOVWF	CONTADOR2	;INICIA CONTADOR2
	DECFSZ	CONTADOR3	;REDUZ CONTADOR3
	GOTO	ATRASO2		;CHAMA ATRASO2 SE NAO FOR 0
	BSF		LED5

	RETURN				;SE FOR IGUAL A 0, RETORNA


ATRASO2
	MOVLW	254
	MOVWF	CONTADOR1	;INICIA CONTADOR1
	DECFSZ  CONTADOR2	;REDUZ CONTADOR2
	GOTO	ATRASO1		;CHAMA ATRASO1 SE NAO FOR 0
	BCF		LED5
; CHECAR BOTAO DEPOIS DE ATRASO 2 ( +- 47.6mS )
	BTFSS	BOTAO
	GOTO	BOTAOPRESSIONADO
	GOTO	ATRASO3		;SE FOR IGUAL A 0, VOLTA PARA ATRASO3


ATRASO1
	DECFSZ	CONTADOR1	;REDUZ CONTADOR ATE SER IGUAL A 0
	GOTO	ATRASO1
	GOTO 	ATRASO2		;DEPOIS VOLTA PARA ATRASO2	

; CHECAR A PARTIR DE QUAL BOTAO COMECAR
BOTAOPRESSIONADO
	BTFSC	LED4
	GOTO	BOTAO4
	BTFSC	LED3
	GOTO	BOTAO3
	BTFSC	LED2
	GOTO	BOTAO2
	BTFSC	LED1
	GOTO 	BOTAO1
	GOTO	BOTAO0

; ATRASO DE 2S NO BOTAO ATUAL E TROCAR PARA O ANTERIOR
BOTAO4
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	BCF LED4
	BSF LED3
	GOTO BOTAO3
	
	
BOTAO3
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	BCF LED3
	BSF LED2
	GOTO BOTAO2
	
	
BOTAO2
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	BCF LED2
	BSF LED1
	GOTO BOTAO1
	
	
BOTAO1
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	BCF	LED1
	BSF	LED0
	GOTO BOTAO0
	
; ATRASO DE 10S NO TERREO
BOTAO0
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	CALL ATRASOBOTAO
	GOTO REPETE
	
; ATRASO DE 1S NO BOTAO
ATRASOBOTAO
	MOVLW	12
	MOVWF	CONTADOR3	;INICIA CONTADOR3


ATRASOBOTAO3				
	MOVLW	140
	MOVWF	CONTADOR2	;INICIA CONTADOR2
	DECFSZ	CONTADOR3	;REDUZ CONTADOR3
	GOTO	ATRASOBOTAO2		;CHAMA ATRASO2 SE NAO FOR 0
	BSF 	LED5		;LIGAR LED5 ( INICIO PISCADA )
	RETURN				;SE FOR IGUAL A 0, RETORNA


ATRASOBOTAO2
	MOVLW	216
	MOVWF	CONTADOR1	;INICIA CONTADOR1
	DECFSZ  CONTADOR2	;REDUZ CONTADOR2
	GOTO	ATRASOBOTAO1		;CHAMA ATRASO1 SE NAO FOR 0
	BCF LED5			; DESLIGAR LED5
	GOTO	ATRASOBOTAO3		;SE FOR IGUAL A 0, VOLTA PARA ATRASO3


ATRASOBOTAO1
	DECFSZ	CONTADOR1	;REDUZ CONTADOR ATE SER IGUAL A 0
	GOTO	ATRASOBOTAO1
	GOTO 	ATRASOBOTAO2		;DEPOIS VOLTA PARA ATRASO2
	RETURN


	END			;OBRIGATÓRIO

